# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: splunk-pvc
# spec:
#   accessModes:
#     - ReadWriteOnce
#   resources:
#     requests:
#       storage: 50Gi

---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: pd-balanced-csi
provisioner: ebs.csi.aws.com
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
parameters:
  type: gp3
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: splunk-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: pd-balanced-csi
  resources:
    requests:
      storage: 50Gi