apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-repo-server
  namespace: argocd
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: argocd-repo-server
  template:
    metadata:
      labels:
        app.kubernetes.io/name: argocd-repo-server
    spec:
      containers:
        - name: repo-server
          image: quay.io/argoproj/argocd:v2.10.7
          command: ["/usr/local/bin/argocd-repo-server"]

kubectl apply -f argocd-repo.yaml
